const createOrUpdateInvoice = require("../../model/services/invoice/createTempinvoice");

const postCreateTempNewInvoice = async (req, res, next) => {
    try {
        /* 
        Receive the input with invoice summary. 
        If there is any record without a displayId, it will send back the response indicating that the cart has already been generated by the user. 
        Otherwise, it will create a new object and send the document as a response.
        */


        // for dummy content Capture the input data from the request
        const data = req.body;
        console.log(data, 'input from front end for creating new temporary invoice ')
        // Construct the result object from the database 
        const result = await createOrUpdateInvoice(data)
        console.log(result)
        if (result) {
            const responce = {
                status: true,
                message: '',
                data: result
            };
            // Send back the response with the received data
            res.json(responce);
        }
        else {
            res.json({
                status: false,
                message: 'operation failed ',
                 
            })
        }
    } catch (error) {
        // Pass any error to the next middleware for handling
        next(error);
    }
};

module.exports = postCreateTempNewInvoice;
